### PR TITLE
fix: apply fixes to basic multicast scenario

### LINKED ISSUE #55: Blockwise transfer during multicast not working properly
If a Client sends a multicast request and receives a response using blockwise transfer, it seems as if the client is currently not switching to a unicast transfer to handle the remaining blocks (c. f. [RFC 7959, section 2.8](https://datatracker.ietf.org/doc/html/rfc7959#section-2.8)). This causes problems as subsequent blocks will also be requested from the multicast address which leads to an exponential(?) growth of requests and responses (if multiple servers are part of the same group and provide a similar resource) until a final block has been reached while also corrupting the total payload.

I will try to provide a fix for this problem in the upcoming days.

### PR DESCRIPTION
**Pull request by JKRhb**
This PR applies a couple of fixes/changes to the project in order to make it possible to use simple (i. e. non-blockwise) multicast requests. To achieve this, multicast requests are no longer being able to be sent as confirmable messages (c. f. [RFC 7252, section 8.1](https://datatracker.ietf.org/doc/html/rfc7252#section-8.1)). Instead, all confirmable multicasts requests are converted to non-confirmable ones. Furthermore, multicast requests are no longer being labelled as complete after the first response and multiple responses no longer marked as duplicates.

I guess the solution is probably not perfect yet (and does not resolve #55 yet), but I guess it is a step into the right direction. Feedback is highly appreciated :)

### CODE REVIEW

**Comment by shamblett** [comment]
OM I've merged some of your earlier PR's and re released the package at version 3.4.1. I'll look at this in relation to #55 hopeully shortly.

File: lib/src/net/coap_matcher.dart [hunk 1]
```diff
@@ -236,10 +236,14 @@ class CoapMatcher implements CoapIMatcher {
     var keyId = CoapKeyId(response.id);
     final keyToken = CoapKeyToken(response.token);
     final exchange = _exchangesByToken[keyToken];
+    final multicast = exchange?.request?.multicast ?? false;
     if (exchange != null) {
       // There is an exchange with the given token
       final prev = _deduplicator!.findPrevious(keyId, exchange);
       if (prev != null) {
+        if (multicast) {
+          return prev;
```
Comment (shamblett) [inline lib/src/net/coap_matcher.dart:245]: Maybe a log line here saying we are returning prev because of multicast processing, may help in debugging this at run time.

**Comment by shamblett** [comment]
Nothing strikes me as being odd here but I guess that eventually we will have to go with something and get feedback as to actual behavior by testing, its a difficult area to work in.

It almost looks as though we need a special multicast endpoint maybe, rather than varying the behavior of the general one then of course we would have to instantiate when needed which may be problematic in itself.

Lets see where we go with the changes so far.

File: lib/src/net/coap_matcher.dart (hunk 1 above)
Comment (JKRhb) [reply lib/src/net/coap_matcher.dart:245]: Good point! Maybe something like this? 

```suggestion
          _log!.info('Matcher - Reuse exchange for multicast processing');
          return prev;
```

**Comment by JKRhb** [comment]
> It almost looks as though we need a special multicast endpoint maybe, rather than varying the behavior of the general one then of course we would have to instantiate when needed which may be problematic in itself.

That is a good idea! This might also make it easier to deal with the blockwise case. I will try it out in the context of #56.
